package com.example.diskwizard.domain.service.disk;

import com.example.diskwizard.domain.model.Disk;

import java.util.ArrayList;
import java.util.List;

public class LocalDiskService implements DiskService {

    @Override
    public List<Disk> getAll() {
        return new ArrayList<Disk>() {{
            add(new Disk("Test 1", "Test 1 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 2", "Test 2 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 3", "Test 3 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 4", "Test 4 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 5", "Test 5 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 6", "Test 6 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 7", "Test 7 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 1", "Test 1 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 2", "Test 2 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 3", "Test 3 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 4", "Test 4 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 5", "Test 5 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 6", "Test 6 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 7", "Test 7 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 1", "Test 1 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 2", "Test 2 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 3", "Test 3 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 4", "Test 4 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 5", "Test 5 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 6", "Test 6 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
            add(new Disk("Test 7", "Test 7 description", "Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details Test details"));
        }};
    }

}
